frenscollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('profiles/', views.profiles_index, name='index.profile'),
    path('profiles/<int:profile_id>/', views.profiles_detail, name='detail.profile'),
    path('frens/', views.frens_index, name='index.fren'),
    path('frens/<int:fren_id>/', views.frens_detail, name='detail.fren'),
    path('profiles/create/', views.ProfileCreate.as_view(), name='profiles_create'),
    path('profiles/<int:pk>/update', views.ProfileUpdate.as_view(), name='profiles_update'),
    path('profiles/<int:pk>/delete', views.ProfileDelete.as_view(), name='profiles_delete'),
    path('profiles/<int:profile_id>/add_theme/', views.add_theme, name='add_theme'),
    path('frens/create/', views.FrenCreate.as_view(), name='frens_create'),
    path('frens/<int:pk>/update', views.FrenUpdate.as_view(), name='frens_update'),
    path('frens/<int:pk>/delete', views.FrenDelete.as_view(), name='frens_delete'),
    path('profiles/<int:profile_id>/request_fren/<int:fren_id>', views.request_fren, name='request_fren')
]

main_app/models.py
from django.db import models
from django.urls import reverse

class Fren(models.Model):
    # name = models.ManyToManyField(Profile)
    nickname = models.CharField(max_length=24)
    most_favorite_color = models.CharField(max_length=24, default='Xanadu??')
    first_met = models.DateField()
    favorite_thing = models.TextField(max_length=240)
    super_fren_status = models.BooleanField('Are you two super frens?!')

    def __str__(self):
        return self.nickname

    def get_absolute_url(self):
        return reverse('detail.fren', kwargs={'pk': self.id})

class Profile(models.Model):
    name = models.CharField(max_length=24)
    age = models.IntegerField()
    description = models.TextField(max_length=240)
    frens = models.ManyToManyField('self', through='Fren')
    fren = models.ManyToManyField(Fren)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail.profile", kwargs={"profile_id": self.id})


class Theme(models.Model):
    name = models.CharField(max_length=48)
    description = models.TextField(max_length=250)
    favorite_color = models.CharField(max_length=24, default='Blue?')
    upload = models.ImageField(upload_to='main_app/static/images/')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main_app/forms.py
from django.forms import ModelForm
from .models import Theme

class ThemeForm(ModelForm):
    class Meta:
        model = Theme
        fields = ['name', 'description', 'favorite_color', 'upload'] # or '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Fren, Profile 
from django.views.generic import ListView
from .forms import ThemeForm 

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def profiles_index(request):
    profiles = Profile.objects.all()
    return render(request, 'profiles/index.html', { 'profiles': profiles })

def profiles_detail(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    id_list = profile.fren.all().values_list('id')
    frens_you_dont_have = Fren.objects.exclude(id__in=id_list)
    theme_form = ThemeForm()
    return render(request, 'profiles/detail.html', { 
        'profile': profile, 'theme_form': theme_form, 'frens': frens_you_dont_have 
    })

def frens_index(request):
    frens = Fren.objects.all()
    return render(request, 'frens/index.html', { 'frens': frens})

def frens_detail(request, fren_id):
    fren = Fren.objects.get(id=fren_id)
    return render(request, 'frens/detail.html', { 'fren': fren })

class ProfileCreate(CreateView):
    model = Profile
    fields = ['name', 'age', 'description'] # no more __all__ to bypass frens
    success_url = '/profiles/'

class ProfileUpdate(UpdateView):
    model = Profile
    fields = ['name', 'age', 'description']  # avoids frens preemptively

class ProfileDelete(DeleteView):
    model = Profile
    success_url = '/profiles/'

class FrenCreate(CreateView):
    model = Fren
    fields = ['nickname', 'most_favorite_color', 'first_met', 'favorite_thing', 'super_fren_status'] # no more __all__ to bypass frens
    success_url = '/frens/'

class FrenUpdate(UpdateView):
    model = Fren
    fields = ['nickname', 'most_favorite_color', 'first_met', 'favorite_thing', 'super_fren_status']  # '__all__'


class FrenDelete(DeleteView):
    model = Fren
    success_url = '/frens/'

def add_theme(request, profile_id):
    form = ThemeForm(request.POST)
    if form.is_valid():
        new_theme = form.save(commit=False)
        new_theme.profile_id = profile_id
        new_theme.save()
    return redirect('detail.profile', profile_id)

def request_fren(request, profile_id, fren_id):
    Profile.objects.get(id=profile_id).fren.add(fren_id)
    return redirect('detail.profile', profile_id=profile_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Fren Collector</h1>
<hr />
<p>Hire the Fren Collector ^_^!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fren Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
<header class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
        <ul>
            <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Fren Collector</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'index.profile' %}">Profiles!</a></li>
            <li><a href="{% url 'frens_create' %}">Add a Fren!</a></li>
            <li><a href="{% url 'index.fren' %}">Fren Party</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
        </ul>
        </div>
    </nav>
</header>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
<footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Fren Collector &nbsp;</div>
</footer>
</body>
</html>

main_app/templates/frens/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Fren Details! =D</h1>

<div class="card">
    <div class="card-content">
        <spam class="card-title" style="color: {{ fren.most_favorite_color }}">'{{ fren.nickname}}'</span>
        <p style="color: {{ fren.most_favorite_color }}">Most Favorite Color: {{ fren.most_favorite_color }}</p>
        <p>Description: {{ fren.description|linebreaks }}</p>
        <p>First Met: {{ fren.first_met }}</p>
        <p>Favorite Trait: {{ fren.favorite_thing }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'frens_update' fren.id %}">Edit</a>
        <a href="{% url 'frens_delete' fren.id %}">Delete</a>
    </div>
</div>

<script>
    const dateEl = document.getElementById('id_first_met');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>

{% endblock %}

main_app/templates/frens/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Fren Party</h1>

{% for fren in frens %}
    <div class="card">
        <a href="{% url 'detail.fren' fren.id %}">
            <div class="card-content">
                <spam class="card-title">'{{ fren.nickname}}' {{ fren.name }}</span>
                <p>Age: {{ fren.age }}</p>
                <p>Description: {{ fren.description|linebreaks }}</p>
                <p>First Met: {{ fren.first_met }}</p>
                <p>Favorite Trait: {{ fren.favorite_thing }}</p>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}


{% for profile in profiles %}
    <div class="card">
        <a href="{% url 'detail' profile.id %}">
            <div class="card-content">
                <spam class="card-title">{{ profile.name }}</span>
                <p>Age: {{ profile.age }}</p>
                <p>Description: {{ profile.description|linebreaks }}</p>
            </div>
        </a>
    </div>
{% endfor %}

<div class="card">
    <a href="{% url 'profiles_create' %}">Create Profile!</a>
</div>


{% endblock %}

main_app/templates/main_app/fren_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Fren</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>? ;_;</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes; Delete!! ~=V" class="btn">
    <a href="{% url 'detail.fren' fren.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/fren_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.nickname}}</span></h1>
{% else %}
    <h1>Add Fren =P !!</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
<!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

<script>
    const dateEl = document.getElementById('id_first_met');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>

{% endblock %}

main_app/templates/main_app/profile_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Profile</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>? ;_;</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes; Delete!! ~=V" class="btn">
    <a href="{% url 'detail.profile' profile.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Profile =P !!</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
<!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/profiles/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Profile Details</h1>

<div class="card">
    <div class="card-content">
            <spam class="card-title">{{ profile.name }}</span>
            <p>Age: {{ profile.age }}</p>
            <p>Description: {{ profile.description|linebreaks }}</p>
        <div class="card-action">
            <a href="{% url 'profiles_update' profile.id %}">Edit</a>
            <a href="{% url 'profiles_delete' profile.id %}">Delete</a>
        </div>
    </div>
</div>

<hr>
    <div class="row">
        <div class="col s6">
        <h3>{{ profile.name }}'s Frens !</h3>
            {% if profile.fren.count %}
            {% for fr in profile.fren.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        <span style="color: {{ fr.most_favorite_color }}"><strong>{{ fr.nickname }}</strong></span>
                        <p>We first met: {{ fr.first_met }}</p>
                        <p>My favorite thing about them is: {{ fr.favorite_thing }}</p>
                        <p>Are you two... Super frens?!:</p> <h3 style="color: {{ fr.most_favorite_color }}">{{ fr.super_fren_status|yesno:'Hells yeah!,no way !!' }}</h3>
                    </span>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5>No frens :( </h5>
            <div class="card">
                <div class="card-content">
                    <a href="{% url 'frens_create' %}" id="add-fren-link">Add a Fren!</a>
                </div>
            </div>
            {% endif %}
        </div>
        <!-- Available frens will come after this line -->
        <div class="col s6">
            <h3>Available frens !!</h3>
            {% if frens.count %}
            {% for fren in frens.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            <span style="color: {{ fren.most_favorite_color }}"><strong>{{ fren.nickname }}</strong></span>
                        </span>
                    </div>
                    <div class="card-action">
                    <form action="{% url 'request_fren' profile.id fren.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn">add fren</button>
                    </form>
                    </div>
                </div>
            {% endfor %}
            {% else %}
                <h5>{{profile.name}} Already Has All frens Available</h5>
            {% endif %}
        </div>
    </div>

    <div class="col s6">
        <form action="{% url 'add_theme' profile.id %}" method="post">
            {% csrf_token %}
            {{ theme_form.as_p }}
            <input type="submit" class="btn" value="Add Theme">
        </form>

        <table class="striped">
            <thead>
                <tr><th>Name</th><th>Description</th><th>Favorite Thing</th></tr>
            </thead>
            <tbody>
            {% for theme in profile.theme_set.all %}
                <tr>
                    <td style="color: {{ theme.favorite_color }}">{{theme.name}}</td>
                    <td style="color: {{ theme.favorite_color }}">{{theme.description}}</td>
                    <td style="color: {{ theme.favorite_color }}">{{theme.favorite_thing}}</td>
                </tr>
                <tr>
                    <td><img src="{% static '{{ theme.upload }}' %}" alt="vsCode Color Theme"></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

<script>
    const dateEl = document.getElementById('id_first_met');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>

{% endblock %}

main_app/templates/profiles/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Profile Viewing </h1>

{% for profile in profiles %}
    <div class="card">
        <a href="{% url 'detail.profile' profile.id %}">
            <div class="card-content">
                <spam class="card-title">{{ profile.name }}</span>
                <p>Age: {{ profile.age }}</p>
                <p>Description: {{ profile.description }}</p>
            </div>
        </a>
    </div>
{% endfor %}

{% for profile in profiles %}
            {% if profile not in request.profile.frens.all and profile != fren_request.from_profile %}
            {{ profile }} <a href="/send_fren_request/{{ profile.id }}/">Send Fren Request!!</a>
            {% endif %}
            {% for fren_request in all_fren_requests %}
            {{ fren_request.from_profile }}
            <a href="/accept_fren_request/{{ fren_request.id }}/">
                Accept Fren Request!!</a>
            {% endfor %}
            {% endfor %}

{% comment %} {% for fren in frens %}
    <div class="card">
        <a href="{% url 'detail' fren.id %}">
            <div class="card-content">
                <spam class="card-title">'{{ fren.nickname}}' {{ fren.name }}</span>
                <p>Age: {{ fren.age }}</p>
                <p>Description: {{ fren.description|linebreaks }}</p>
                <p>First Met: {{ fren.first_met }}</p>
                <p>Favorite Trait: {{ fren.favorite_thing }}</p>
            </div>
        </a>
    </div>
{% endfor %} {% endcomment %}

{% endblock %}